### PR TITLE
Lesson 8 Assignment 1

### PR DESCRIPTION
**Pull request by HiroTestStudent**
Hi Luis,

I worked on Lesson 8 assignment 1. I got stuck on neo4j assignment so it is incomplete. For the rest of assignment 1, I think they should cover what the question asked. 

Thanks,
Hiro

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Hiro,

Aside from neo4j, was the rest of your implementation working? I get the following output while running (showing an error with one the keys for your MongoDB implementation:

```
$ python learnnosql.py
2019-01-06 19:43:18 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-06 19:43:18 - INFO - Here is where we use the connect to mongodb.
2019-01-06 19:43:18 - INFO - Note use of f string to embed the user & password (from the tuple).
error: 'mongodb_cloud'
2019-01-06 19:43:18 - INFO - Step 1: We are going to use a database called dev
2019-01-06 19:43:18 - INFO - But if it doesnt exist mongodb creates it
2019-01-06 19:43:18 - INFO - And in that database use a collection called furniture
2019-01-06 19:43:18 - INFO - If it doesnt exist mongodb creates it
2019-01-06 19:43:18 - INFO - Step 2: Now we add data from the dictionary above
2019-01-06 19:43:19 - INFO - Step 3: Find the products that are described as plastic
2019-01-06 19:43:20 - INFO - Step 4: Print the plastic products
Plastic products
{'_id': ObjectId('5c32ca8c395aaf7009c0f2be'),
 'color': 'Red',
 'description': 'Plastic',
 'in_stock_quantity': 45,
 'monthly_rental_cost': 1.0,
 'product_type': 'Chair'}
2019-01-06 19:43:20 - INFO - Step 5: Delete the blue couch (actually deletes all blue couches)
2019-01-06 19:43:20 - INFO - Step 6: Check it is deleted with a query and print
The blue couch is deleted, print should show none:
None
2019-01-06 19:43:20 - INFO - Step 7: Find multiple documents, iterate though the results and print
Results of search
2019-01-06 19:43:20 - INFO - Notice how we parse out the data from the document
Traceback (most recent call last):
  File "learnnosql.py", line 39, in <module>
    showoff_databases()
  File "learnnosql.py", line 25, in showoff_databases
    mongodb_script.run_example(furniture)
  File "/Users/ldconejo/Documents/Personal/Teaching_at_UW/courseGit/students/HiroyukiTakechi/Lesson8/nosql-master/src/mongodb_script.py", line 55, in run_example
    print(f"Cost: {doc['monthly_rental_cost']} product name: {doc['product']} Stock: {doc['in_stock_quantity']}")
KeyError: 'product'
```

Thanks,

Luis

**Comment by HiroTestStudent** [comment]
Hi Luis,

Sorry I forgot to run the files. I have been overloaded by my Apple tasks so I am having difficult time to juggle with UW assignments. I will try to find time by our office hours on Wednesday to run lesson 8 files.

Can we check how much left to do during office hours? I am under severe time crunch and it will get worse since Jan to May is peak period at work. 

Thanks,
Hiro

**Comment by ldconejo** [comment]
Hi Hiro,

Please submit the assignment on the course website, so that I can grade it.

Thanks,

Luis

**Comment by HiroTestStudent** [comment]
Hi Luis,

I just submitted the Lesson 8 assignment 1 to the course website.

Thanks!
Hiro

**Pull request merged**
