### PR TITLE
Lesson 06

### PR DESCRIPTION
**Pull request by rbillupsii**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Roy,

For the calculator assignment, your integration test is failing:

```
$ python -m unittest integration-test.py 
F
======================================================================
FAIL: test_module (integration-test.ModuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ldconejo/Documents/UW/courseGit/students/RoyC/lesson06/calculator/integration-test.py", line 35, in test_module
    self.assertEqual(6, result)
AssertionError: 6 != 0.8571428571428572
```

Other than that, everything else in the assignment works great.

-Luis

**Comment by ldconejo** [comment]
For the water regulation project, both _test.py_ and _integrationtest.py_ need to be set so that _unittest_ can invoke them for one level up:

$ python -m unittest waterregulation/test.py
$ python3 -m unittest waterregulation/integrationtest.py

Please submit a new pull request once that's corrected.

Thanks,

Luis

**Comment by rbillupsii** [comment]
Luis,

 

I was confused about your request at first since these tests worked for me, but then I realized I failed to commit all of the files in the directories. I hopefully resolved that with this pull request:

 

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018/pull/636

 

Thanks,

Roy

**Comment by rbillupsii** [comment]
Luis,

 

I was pretty sure this worked for me at one point so I probably broke it with one of the later assignment steps. I did fix it and included the changes in my second pull request:

 

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018/pull/636

 

Thanks,

Roy

**Pull request closed without merging**
