### PR TITLE
Help with Lesson08 Part1

### PR DESCRIPTION
**Pull request by seaneightysix**
Hi,

I'm having trouble connecting to mangodb. Here is the error message I'm getting:

pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833),SSL handshake failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833),SSL handshake failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

I am absolutely stumped on this. Could you help me on this so I can proceed with the assignment?  

Thanks so much,
Sean

### CODE REVIEW

**Comment by seaneightysix** [comment]
Hi, 
I have corrected my lesson06 mistakes. Lesson06 is now ready for review again. Thank you.

**Comment by ldconejo** [comment]
Hi Sean,

This is possibly related to your setup on not your code (I was able to run your code on my machine), could you take a look at _Troubleshooting TLS Errors_ under this link:

http://api.mongodb.com/python/current/examples/tls.html

Let me know if none of the solutions suggested there help you with your issue.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Sean,

Good that the first error is gone. Could you check which Pymongo version are you using? Open a Python console and type the following:

import pymongo
pymongo.__version__

This is just to discard that you're using an older version. Also, check the connection string on line 33 of _login_database.py_ and make sure it matches yours.

-Luis

**Comment by seaneightysix** [comment]
3.3.0

**Comment by seaneightysix** [comment]
Yes, I have verified that the connection string is correct.

**Comment by ldconejo** [comment]
Ok, 3.3.0 is a little old (as a reference, I'm running on 3.7.0). Could you go ahead and update it to the latest version and try again?

Thanks,

Luis

**Comment by seaneightysix** [comment]
I updated pymango to 3.7.0 and that solved my previous problem, but I am
now getting a different error:

**Comment by seaneightysix** [comment]
I updated pymango to 3.7.0 and that solved my previous problem, but I am
now getting a different error:

pymongo.errors.OperationFailure: bad auth Authentication failed.


I have hardcoded my user id and password into the connection string:


client = pymongo.MongoClient(f'mongodb://
stasaki:Bostoneastboston99%2A@cluster0-shard-00-00-ez67j.mongodb.net:27017,
cluster0-shard-00-01-ez67j.mongodb.net:27017,
cluster0-shard-00-02-ez67j.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
')



Do you have any idea what I'm missing?

**Comment by ldconejo** [comment]
Hi Sean,

Your connection string is very similar to mine, the same code passes with mine and fails with yours. I wonder if the special character in your password is causing issues: You have "%2A" as part of the password, which is HTML URL encoding for "*". In any case, try a simpler password, like "test01". You'll need to log into your MongoDB account on their website and make this change. Then try again with the hardcoded string.

Regards,

Luis

**Comment by ldconejo** [comment]
Hi Sean,

I'm glad you found the error. Good debug last night!

-Luis

**Pull request closed without merging**
