### PR TITLE
Lesson06 complete

### PR DESCRIPTION
**Pull request by seaneightysix**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Sean,

For the calculator assignment, unit and integration testing and coverage analysis are good, you need to do a few corrections for Pylint analysis:

```
$ python -m pylint calculator
************* Module calculator.subtracter
calculator/subtracter.py:6:0: C0111: Missing class docstring (missing-docstring)
calculator/subtracter.py:9:4: C0111: Missing method docstring (missing-docstring)
calculator/subtracter.py:6:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module calculator.multiplier
calculator/multiplier.py:1:0: C0111: Missing module docstring (missing-docstring)
calculator/multiplier.py:1:0: C0111: Missing class docstring (missing-docstring)
calculator/multiplier.py:4:4: C0111: Missing method docstring (missing-docstring)
calculator/multiplier.py:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module calculator.divider
calculator/divider.py:1:0: C0111: Missing module docstring (missing-docstring)
calculator/divider.py:1:0: C0111: Missing class docstring (missing-docstring)
calculator/divider.py:4:4: C0111: Missing method docstring (missing-docstring)
calculator/divider.py:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module calculator.calculator
calculator/calculator.py:44:0: C0305: Trailing newlines (trailing-newlines)
calculator/calculator.py:1:0: C0111: Missing module docstring (missing-docstring)
calculator/calculator.py:5:0: C0111: Missing class docstring (missing-docstring)
calculator/calculator.py:17:4: C0111: Missing method docstring (missing-docstring)
calculator/calculator.py:23:26: W1202: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
calculator/calculator.py:25:26: W1202: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
calculator/calculator.py:32:4: C0111: Missing method docstring (missing-docstring)
calculator/calculator.py:35:4: C0111: Missing method docstring (missing-docstring)
calculator/calculator.py:38:4: C0111: Missing method docstring (missing-docstring)
calculator/calculator.py:41:4: C0111: Missing method docstring (missing-docstring)
calculator/calculator.py:2:0: C0411: standard import "import logging" should be placed before "from .exceptions import InsufficientOperands" (wrong-import-order)
************* Module calculator.exceptions
calculator/exceptions.py:1:0: C0111: Missing module docstring (missing-docstring)
calculator/exceptions.py:1:0: C0111: Missing class docstring (missing-docstring)
************* Module calculator.adder
calculator/adder.py:1:0: C0111: Missing module docstring (missing-docstring)
calculator/adder.py:1:0: C0111: Missing class docstring (missing-docstring)
calculator/adder.py:4:4: C0111: Missing method docstring (missing-docstring)
calculator/adder.py:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)

-------------------------------------------------------------------
Your code has been rated at 3.49/10 (previous run: 10.00/10, -6.51)
```

Don't worry about the _Too few public methods_ warning, but the others should be relatively easy to fix.

Flake8 also has a couple of issues that need to be fixed:

```
$ python -m flake8 calculator
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
calculator/calculator.py:21:5: E303 too many blank lines (2)
calculator/calculator.py:23:80: E501 line too long (82 > 79 characters)
calculator/calculator.py:25:80: E501 line too long (99 > 79 characters)
calculator/calculator.py:44:1: W391 blank line at end of file
```

Regards,

Luis

**Comment by ldconejo** [comment]
For the water regulation assignment, similar issues with Pylint and several issues with Flake8. Also, your unit and integration tests have to be coded such that they can be called from outside of the _waterregulation_ directory.

Let me know if you have any questions on these.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Sean,

I saw the updates for the calculator project. For the water regulation one, there are still a number of issues with Pylint:

```
$ python -m pylint waterregulation/
************* Module waterregulation.sensor
waterregulation/sensor.py:8:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module waterregulation.controller
waterregulation/controller.py:5:0: W0401: Wildcard import waterregulation.decider (wildcard-import)
waterregulation/controller.py:47:15: W0703: Catching too general exception Exception (broad-except)
waterregulation/controller.py:47:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
waterregulation/controller.py:32:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
************* Module waterregulation.decider
waterregulation/decider.py:50:8: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
waterregulation/decider.py:50:8: R0911: Too many return statements (7/6) (too-many-return-statements)
************* Module waterregulation.pump
waterregulation/pump.py:34:64: C0303: Trailing whitespace (trailing-whitespace)
```

Regards,

Luis

**Comment by seaneightysix** [comment]
Hi Luis,
I have made the corrections for both lesson06 and lesson07.

Thanks,
Sean

**Pull request closed without merging**
