### PR TITLE
Committing the lesson 6 calculator assignment

### PR DESCRIPTION
**Pull request by willhwhite**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Will,

I see this pull contains multiple submissions, I do have some inputs on a some of them:

For lesson 3:

- On the locke assignment, try to do exception handling so that the program doesn't crash, this can be achieved by adding some additional code to the __exit_()_ method (the following is some sample code from another student):

```
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is ValueError:
            print(exc_val) 
        return True
```

- On the recursion assignment for lesson 3, you need to do a separate submission on the course's website, so that I can grade that part.

- On the calculator assignment (lesson 6), unit and integration testing are working great, coverage is at 100% and Pylint is passing. However, the following errors are reported by Flake8:

```
$ python -m flake8 calculator/
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
calculator/divider.py:13:80: E501 line too long (98 > 79 characters)
calculator/calculator.py:2:80: E501 line too long (85 > 79 characters)
calculator/calculator.py:10:80: E501 line too long (93 > 79 characters)
calculator/calculator.py:31:80: E501 line too long (80 > 79 characters)
calculator/exceptions.py:8:80: E501 line too long (97 > 79 characters)
calculator/adder.py:5:1: E302 expected 2 blank lines, found 1
```

Please take a look and see if you can fix those warnings, should be relatively easy. You can reopen this pull request once you have the necessary changes implemented.

Thanks,

Luis

**Comment by willhwhite** [comment]
Hey Luis,

Thanks for all the feedback, I have made the updates and am ready to
resubmit the assignments.

It looks like files have been submitted for both assignments in Lesson 03,
but they contain the same zip folder, so I am unable to submit recursion on
its own. Please let me know if you're seeing something different on your
end.

Also, I assume in order to capture the above changes, you'd like me to
recommit, push, and create a brand new pull request. Is this correct, or
does "reopen this pull request" mean something different?

Thanks!
Will

**Comment by willhwhite** [comment]
Hey Luis,

Hope you had a nice thanksgiving break. I'm just following up on the above
response. Let me know if you have any questions.

Thanks,
Will

**Comment by ldconejo** [comment]
Hi Will,

It seems I missed this one. Could you update this pull request with your changes?

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Will,

I have reviewed and graded both assignment 3 and the calculator assignment from lesson 6. Great work on both.

Regards,

Luis

**Pull request merged**
