### PR TITLE
Lesson2: solution for excercises

### PR DESCRIPTION
**Pull request by JeroenSweerts**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Jeroen,

Could you also enter a submission on the course website for lesson 1? I need that in order to grade that assignment. I'll grade only lesson 2 for now.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Jeroen,

For the closures portion, the intent is that your function will capture high energy tracks (0.8 or higher), right now, it is returning all information for all tracks. Please modify your code to return energy=0.8 or higher and simplify the data output to show only track name, artist and energy level.

Thanks,

Luis

**Comment by JeroenSweerts** [comment]
Hello Luis,

I already submitted lesson1 and it was reviewed
 Do you want me to resubmit?

Will be travelling for the next 2 weeks but will resubmit when i'm back on 4th april.

Best regards,

Jeroen



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ldconejo** [comment]
Code for the generator looks good. Please submit an update on the closures section to get the full grade.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Jeroen,

You're correct. That was my bad, for some reason, lesson 1 it wasn't showing as graded. It is now. Have a safe trip!

-Luis

**Comment by JeroenSweerts** [comment]
Hello Luis,

I corrected the code for the closure and made a new pull request (https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018/pull/687).

But I don't know how to resubmit my solution through the course website.

Attached is the zip file with my corrected code. Is this sufficient or should I resubmit in an other way? I so, could you please explain how I do that?

Thanks.


Best regards,


Jeroen



Op 24/03/19 om 16:45 schreef Luis Conejo-Alpizar:

Code for the generator looks good. Please submit an update on the closures section to get the full grade.

Thanks,

Luis

**Pull request closed without merging**
