### PR TITLE
Lesson06

### PR DESCRIPTION
**Pull request by ghassan24601**

### CODE REVIEW

**Comment by ghassan24601** [comment]
Thanks for the feedback. I have pushed the recommended changes in a new commit. 
Please let me know if I'm missing anything else :)
Thank you!

**Comment by ldconejo** [comment]
Hi Ghassan,

Great progress. There are still a couple of issues I noticed:

- You haven't submitted the first part of the assignment in the course, only the second part. Please submit the first part as well so that we can grade it.

- On the water regulation exercise, you used the name _app_test_ in _integrationtest.py_. Because of this, _app_test_ will not be recognized by unittest and won't be tested. Try renaming it with a _test_ prefix and run it. There's an issue there.

Thanks,

Luis

**Comment by ghassan24601** [comment]
- Did you mean the calculator by first part? I thought it was included in this PR.

- Noted. I will fix this one.
Thank you!

**Comment by ghassan24601** [comment]
Fixed. The integrationtest should be calling test_app function now.
Thanks!

**Comment by ldconejo** [comment]
Works as expected now :-) On the assignment submission, in the course itself, you only submitted the second assignment, not the first one ("Advanced Testing"), your PR does include both.

**Pull request merged**
