### PR TITLE
Lesson 02

### PR DESCRIPTION
**Pull request by mcbraunie**
Files Submitted

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Micah,

Please update your pull request to only include files within your folder. Currently, you're modifying files in other students' folders.

Thanks,

Luis

**Comment by mcbraunie** [comment]
Instructor,

I sent you an email regarding this issue with the first submission on
August 25 but did not receive further directions on what I need to change
on my end to fix this.

As I mentioned in my previous message, the only change to my repo between
The previous course and this course has been a new computer so my repo was
set up on a new PC. I followed all of the same instructions as before and
am not doing anything other than the instructions provided to push to my
repo from my PC... Can you please advise on why my submissions would be
altering other submissions? I tried Googling suggestions but nothing was
similar.

Thank you,

Micah Braun

**Comment by ldconejo** [comment]
Hi Micah,

I see. Did you follow the instructions below to setup your fork of the class repo?

https://uwpce-pythoncert.github.io/PythonCertDevel/modules/Git.html#setting-up-your-fork-of-the-class-repository 

If so, what issues did you run into?

Thanks,

Luis

**Comment by mcbraunie** [comment]
Hello Instructor,

I did follow the instructions below to setup my forked repo and my initial
issue was that I could not push any files to my fork because I received a
warning that it was in conflict with someone else’s files. I tried deleting
and reinstalling GIT and re-instating the fork on my own PC several times
until it finally seemed to not have any conflicts. But I never deviated
from the instructions and I had never received that warning in the previous
course with my forked repo.

I don’t receive warnings anymore when I go to push my changes. One time it
said I was a few commits behind the master so I issued a “git pull” command
and then everything worked again.

Did I do something wrong?

Thank you,

Micah Braun

**Comment by ldconejo** [comment]
Hi Micah,

I guess you're using Windows and that the issue is with the line endings. Could you re-install Git on your computer and make sure you select _Checkout Windows-style, commit Unix-style line endings_ (see image below)? Once that's done, create a new clone for the class repository, commit your changes for assignments 1 & 2 and send a new pull request. I think that will do the trick.

Thanks,

Luis 

image

**Comment by mcbraunie** [comment]
Instructor,

I *think* that the issue may be resolved. Though, if you notice more
issues, please let me know. I am not aware of what made the difference but
I uninstalled and re-installed Git several times on my PC (a Surface Pro 4
running Windows 10 Pro on a 64 bit OS) I also deleted my original forked
repository and created it once more in case somehow that would make a
difference and restarted my computer several times during the
trouble-shooting ordeal. I'm not sure what did it, but after a few hours,
everything went through without giving me warnings like before. I saved a
.docx file of the warnings in case that would be necessary, but since
everything seems to be working I guess I don't need to ask you about them.

I made a new pull request:
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018/pull/253
(which includes my work for lessons 1 and 2).

Please let me know if there are still issues.

All best,

Micah Braun

**Pull request closed without merging**
