### PR TITLE
updated calculator files

### PR DESCRIPTION
**Pull request by jaredmulholland**
flake8 showed clean for all files
only errors in pylint were 'too few public methods"

### CODE REVIEW

**Comment by jaredmulholland** [comment]
Having some issues with the unit_test.py and decider.py file. I'm sending the details in a separate email. Trying to finish up this weekend. Any help would be appreciated. Thanks!

**Comment by jaredmulholland** [comment]
updated lines 35, 36

**Comment by ldconejo** [comment]
Hi Jared,

Thanks for making the necessary changes for the calculator assignment, for the _too-few-public-methods_, Pylint allows you to disable a warning in-line by adding something like this at the beginning of your code:

```
# pylint: disable=R0903
fds
```

Note that _R0903_ is the code for that particular warning. No need to make any more changes to the calculator assignment. Good job.

-Luis

**Comment by ldconejo** [comment]
On lesson 4, could you give me some details as to what issues you were running into? For now, try to add a "Load JSON file" and "Save to JSON file" option to your current program, as those are the key two features to be implemented on this assignment (using the _json_save_ module).

-Luis

**Comment by jaredmulholland** [comment]
I created a pull request for lesson 4 with a description of the issues I'm
having. Thanks for your help.

Jared

**Comment by jaredmulholland** [comment]
with my unit_test file, I get the errors:
[image: image.png]
I'm having a tough time figuring out how to fix this one. I'm continuing to
look into it, but any hints would be helpful

Thanks,
Jared

**Pull request merged**
