### PR TITLE
Neo4j Script Question

### PR DESCRIPTION
**Pull request by Swt16**
I got the Mongodb and Redis scripts done. I'm a bit stuck on the last part of the Neo4j script.
I can't seem to figure out how to print all the colors, and each person that listed that color as their favorite.

This is what I have for that portion so far.
```
        log.info('Step 6: Print each color and the person that has the color as their favorite')
        for color in ['Black','Blue','Green','Orange','Purple','Red','White','Yellow']:
            cyph = """
              MATCH (c1:Color {name:'%s'})
              -[:Person]->(ppl)
              RETURN ppl
            """ % (color)
            result = session.run(cyph)
            for item in result:
                for names in item.values():
                    print(names)
```

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Shin,

Let me take a look at this one and get back to you. I'm having some issues with my Neo4j setup, I'll update it here as soon as I look at your code.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Shin,

Maybe try something like this:

```
        log.info('Step 6: Print each color and the person that has the color as their favorite')
        for color in ['Black','Blue','Green','Orange','Purple','Red','White','Yellow']:
            cyph = """ MATCH(p1:Person)-[favcolor: COLOR]->(c1:Color{color:'%s'})
            return p1.first_name as first, p1.last_name as last
            """ % (c)
            result = session.run(cyph)
            print("Color " + color + " is the favorite for: ")
            for record in result:
                print(record['first']+' '+record['last'])
```
Let me know if that works.

Luis

**Comment by Swt16** [comment]
I tried that code above, and it didn't work. I tried playing around with the code, and still no luck.

When I switched the direction of the arrows, I think I might have broke something. I get this error when I run the program every time now:

```
$ python neo4j_script.py
2018-11-21 18:37:08 - INFO - Step 1: First, clear the entire database, so we can start over
2018-11-21 18:37:08 - INFO - Running clear_all
2018-11-21 18:37:08 - INFO - Here is where we use the connect to neo4j.
2018-11-21 18:37:08 - INFO -
Traceback (most recent call last):
  File "neo4j_script.py", line 106, in <module>
    run_example()
  File "neo4j_script.py", line 21, in run_example
    driver = login_database.login_neo4j_cloud()
  File "C:\Users\Admin21\Desktop\Python 220\SP_Online_Course2_2018\students\ShinTran\lesson08\nosql\src\login_database.p                                                                                                                                                       y", line 82, in login_neo4j_cloud
    auth=basic_auth(graphenedb_user, graphenedb_pass))
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neo4j\__init__.py", line 108, in drive                                                                                                                                                       r
    return Driver(uri, **config)
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neo4j\__init__.py", line 147, in __new                                                                                                                                                       __
    return subclass(uri, **config)
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neo4j\__init__.py", line 221, in __new                                                                                                                                                       __
    pool.release(pool.acquire())
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 694, in acqui                                                                                                                                                       re
    return self.acquire_direct(self.address)
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 587, in acqui                                                                                                                                                       re_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neo4j\__init__.py", line 218, in conne                                                                                                                                                       ctor
    return connect(address, **dict(config, **kwargs))
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 945, in conne                                                                                                                                                       ct
    raise last_error
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 937, in conne                                                                                                                                                       ct
    connection = _handshake(s, resolved_address, der_encoded_server_certificate, **config)
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 900, in _hand                                                                                                                                                       shake
    connection.init()
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 240, in init
    self.sync()
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 506, in sync
    detail_delta, summary_delta = self.fetch()
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 410, in fetch
    return self._fetch()
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 450, in _fetc                                                                                                                                                       h
    response.on_failure(summary_metadata or {})
  File "C:\Users\Admin21\AppData\Local\Programs\Python\Python37\lib\site-packages\neobolt\direct.py", line 755, in on_fa                                                                                                                                                       ilure
    raise ServiceUnavailable(message)
neobolt.exceptions.ServiceUnavailable: Internal Server Error.

```

**Comment by Swt16** [comment]
Disregard all the errors in my previous comment, it's working again when I tried it in the morning. I don't know why it did that last night.

But back to my code, I tinkered around and finally it got working!

**Pull request closed without merging**
