### PR TITLE
Lesson01 assignment

### PR DESCRIPTION
**Pull request by wpucilow**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Wieslaw,

Please submit this assignment on the course's website and reopen this pull request. Although pull requests are done on Github, we still need you to submit on the website in order to grade your work.

Regards,

Luis

**Comment by wpucilow** [comment]
Hi,

I'm not sure what do you mean by reopening this pull request. Why it has been closed than? this assignment has been submitted as well as Lesson02

Wieslaw

**Comment by wpucilow** [comment]
Hi,
Lesson01 and Lesson02 assignment have been submitted.
Wieslaw

    On ‎Monday‎, ‎September‎ ‎17‎, ‎2018‎ ‎07‎:‎54‎:‎12‎ ‎PM‎ ‎PDT, Luis Conejo-Alpizar <notifications@github.com> wrote:  
 
 
Hi Wieslaw,

Please submit this assignment on the course's website and reopen this pull request. Although pull requests are done on Github, we still need you to submit on the website in order to grade your work.

Regards,

Luis

**Comment by ldconejo** [comment]
Hi Wieslaw,

We normally close (instead of merging) pull requests that have anything pending (such as submission on the website) or elements that need to be debugged by the student. That way, we know that all open pull requests are waiting for review from the instructor and not for any additional input from the student. When this happens, you can add additional modifications to the pull request and then click on "reopen and comment":

image

I have reviewed your new pull request for lessons 1 & 2. Good job!

Regards,

Luis

**Comment by wpucilow** [comment]
Hi,
I have a problem with json_save.zip
in ipython I have run setup.py install
run setup.py install
running install
running bdist_egg
running egg_info
creating json_save.egg-info
writing json_save.egg-info\PKG-INFO
writing dependency_links to json_save.egg-info\dependency_links.txt
writing top-level names to json_save.egg-info\top_level.txt
writing manifest file 'json_save.egg-info\SOURCES.txt'
reading manifest file 'json_save.egg-info\SOURCES.txt'
writing manifest file 'json_save.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\json_save
copying json_save\json_save_dec.py -> build\lib\json_save
copying json_save\json_save_meta.py -> build\lib\json_save
copying json_save\saveables.py -> build\lib\json_save
copying json_save\__init__.py -> build\lib\json_save
creating build\lib\json_save\test
copying json_save\test\test_json_save_dec.py -> build\lib\json_save\test
copying json_save\test\test_json_save_meta.py -> build\lib\json_save\test
copying json_save\test\test_savables.py -> build\lib\json_save\test
copying json_save\test\__init__.py -> build\lib\json_save\test
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\json_save
copying build\lib\json_save\json_save_dec.py -> build\bdist.win-amd64\egg\json_save
copying build\lib\json_save\json_save_meta.py -> build\bdist.win-amd64\egg\json_save
copying build\lib\json_save\saveables.py -> build\bdist.win-amd64\egg\json_save
creating build\bdist.win-amd64\egg\json_save\test
copying build\lib\json_save\test\test_json_save_dec.py -> build\bdist.win-amd64\egg\json_save\test
copying build\lib\json_save\test\test_json_save_meta.py -> build\bdist.win-amd64\egg\json_save\test
copying build\lib\json_save\test\test_savables.py -> build\bdist.win-amd64\egg\json_save\test
copying build\lib\json_save\test\__init__.py -> build\bdist.win-amd64\egg\json_save\test
copying build\lib\json_save\__init__.py -> build\bdist.win-amd64\egg\json_save
byte-compiling build\bdist.win-amd64\egg\json_save\json_save_dec.py to json_save_dec.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\json_save_meta.py to json_save_meta.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\saveables.py to saveables.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\test\test_json_save_dec.py to test_json_save_dec.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\test\test_json_save_meta.py to test_json_save_meta.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\test\test_savables.py to test_savables.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\test\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\json_save\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying json_save.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying json_save.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying json_save.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying json_save.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\json_save-0.4.0-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing json_save-0.4.0-py3.6.egg
Copying json_save-0.4.0-py3.6.egg to c:\users\pucilowskiw\appdata\local\continuum\anaconda3\lib\site-packages
Adding json-save 0.4.0 to easy-install.pth fileInstalled c:\users\pucilowskiw\appdata\local\continuum\anaconda3\lib\site-packages\json_save-0.4.0-py3.6.egg
Processing dependencies for json-save==0.4.0
Finished processing dependencies for json-save==0.4.0
cd examples/
C:\UW_Python_2\Lesson04\wieslaw\json_save\examples
but

pwd
Out[70]: 'C:\\UW_Python_2\\Lesson04\\wieslaw\\json_save'run example_dec.py
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
C:\UW_Python_2\Lesson04\wieslaw\json_save\example_dec.py in <module>()
      5 """
      6 
----> 7 import json_save.json_save_dec as js
      8 
      9 ModuleNotFoundError: No module named 'json_save.json_save_dec'


import json_save.json_save_dec as js
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-72-aae0216a8b1e> in <module>()
----> 1 import json_save.json_save_dec as jsModuleNotFoundError: No module named 'json_save.json_save_dec'

regardsWieslaw

**Pull request closed without merging**
