### PR TITLE
Lesson08 LearnNoSQL

### PR DESCRIPTION
**Pull request by nDruP**
Mongodb took forever to fix. Simple script was pretty weird because everything the assignment asked for was already shown in the examples that were run. The conversion bit was also confusing because I don't see how to convert from one format to another without first converting to python-compatible data.

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Andrew,

I'm assuming this is just your framework and that you're still working to add MongoDB, Redis and Neo4J functionality, respectively. If that's the case, I'll go ahead and close this pull request for now.

Thanks,

Luis

**Comment by ldconejo** [comment]
Closing request while waiting for additional updates.

**Comment by nDruP** [comment]
Yes, I'm still working on mailroom for those 3 implementations.
The first assignment is done though.

**Comment by ldconejo** [comment]
Hi Andrew,

Did you upload the files for the first assignment in lesson 08? There is a _nosql_ folder in the pull request, but it's empty.

Thanks,

Luis

**Comment by ldconejo** [comment]
Good job! The neo4j log you attached was empty, but I was to run your code and verify that all three are doing what's required in the assignment.

**Pull request merged**
