### PR TITLE
Lesson 06 calculator exercise

### PR DESCRIPTION
**Pull request by smitco**

### CODE REVIEW

**Comment by smitco** [comment]
I am getting a pylint error for "too few public methods" on a few of the water regulation files. What does that mean?

Also, if I pylint the whole folder, I get import errors on the two test files as well as duplicate code errors. I don't get those if I pylint the files individually. How should I address those errors?

**Comment by ldconejo** [comment]
Hi Courtney,

The calculator assignment looks grade. For the water regulation assignment, one of the tricks is that you only need to test coverage, Pylint and Flake8 on the two target files, _decider.py_ and _controller.py_. Don't worry about the "too few public methods" warning, as that just a side effect of the implementation. In the water regulation setup, the unit and integration testing files are placed inside of the project folder (not always a good idea in my opinion), so you cannot test the entire folder with Pylint or Flake8, as you will get some of the issues you ran into. It's still a possible scenario in a real world project (test files placed in the same folder). The second assignment looks good, please submit on the course website and I'll go ahead and grade it.

Regards,

Luis

**Comment by ldconejo** [comment]
One more thing, please send me an email once you've submitted the second assignment, as you won't need another pull request for it.

-Luis

**Comment by smitco** [comment]
Thanks Luis. I just submitted the second assignment on the website.

**Pull request merged**
