### PR TITLE
Lesson 08 nosql exercises

### PR DESCRIPTION
**Pull request by smitco**
Lesson 08 first assignment using nosql

### CODE REVIEW

**Comment by smitco** [comment]
The exercise in redis produced a stranger error that I documented with comment lines. Any insight to the issue would be appreciated.

**Comment by ldconejo** [comment]
Hi Courtney,

That's a strange error. I uncommented the offending code and tried it with my own Redis setup, but didn't have the issue. Here's my output (I also changed the search at the end to search for "Jenny" instead of "Jolene"):

```
$ python learnnosql.py
2019-01-01 20:34:10 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-01 20:34:10 - INFO - Other databases use data embedded in the modules
2019-01-01 20:34:10 - INFO - Step 1: connect to Redis
2019-01-01 20:34:10 - INFO - Here is where we use the connect to redis.
2019-01-01 20:34:10 - INFO - Step 2: cache some data in Redis
2019-01-01 20:34:10 - INFO - Step 2: now I can read it
2019-01-01 20:34:10 - INFO - But I must know the key
2019-01-01 20:34:10 - INFO - The results of r.get: andy@somewhere.com
2019-01-01 20:34:10 - INFO - Step 3: cache more data in Redis
2019-01-01 20:34:10 - INFO - Step 4: delete from cache
2019-01-01 20:34:10 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-01 20:34:10 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-01 20:34:10 - INFO - I could use this to generate unique ids
2019-01-01 20:34:10 - INFO - Redis says 21+1+1-1=22
2019-01-01 20:34:10 - INFO - Step 7: richer data for a SKU
2019-01-01 20:34:11 - INFO - Step 8: pull some data from the structure
2019-01-01 20:34:11 - INFO - Type of cover = leather
2019-01-01 20:34:11 - INFO - Step 9: add customer data to cache and retrieve
2019-01-01 20:34:12 - INFO - Jenny's number: 44307 and zip: 867-5309
```

I'll grade the assignment, since it is working as expected on my side, but could you send me the exact error output you get (the one that results in a WRONGTYPE error)?

Thanks,

Luis

**Comment by smitco** [comment]
Okay. Here is the first output when I leave "Jenny" commented out:
(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:40:45 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:40:45 - INFO - Other databases use data embedded in the modules
2019-01-02 09:40:45 - INFO - Step 1: connect to Redis
2019-01-02 09:40:45 - INFO - Here is where we use the connect to redis.
2019-01-02 09:40:45 - INFO - Step 2: cache some data in Redis
2019-01-02 09:40:45 - INFO - Step 2: now I can read it
2019-01-02 09:40:45 - INFO - But I must know the key
2019-01-02 09:40:45 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:40:45 - INFO - Step 3: cache more data in Redis
2019-01-02 09:40:45 - INFO - Step 4: delete from cache
2019-01-02 09:40:45 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:40:45 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:40:46 - INFO - I could use this to generate unique ids
2019-01-02 09:40:46 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:40:46 - INFO - Step 7: richer data for a SKU
2019-01-02 09:40:46 - INFO - Step 8: pull some data from the structure
2019-01-02 09:40:46 - INFO - Type of cover = leather
2019-01-02 09:40:46 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:40:46 - INFO - Jenny commented out
2019-01-02 09:40:48 - INFO - Jolene's number: 37863 and zip: 372-7866

**Comment by smitco** [comment]
Second output with "Jenny" in list:
(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:42:03 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:42:03 - INFO - Other databases use data embedded in the modules
2019-01-02 09:42:03 - INFO - Step 1: connect to Redis
2019-01-02 09:42:03 - INFO - Here is where we use the connect to redis.
2019-01-02 09:42:03 - INFO - Step 2: cache some data in Redis
2019-01-02 09:42:04 - INFO - Step 2: now I can read it
2019-01-02 09:42:04 - INFO - But I must know the key
2019-01-02 09:42:04 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:42:04 - INFO - Step 3: cache more data in Redis
2019-01-02 09:42:04 - INFO - Step 4: delete from cache
2019-01-02 09:42:04 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:42:04 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:42:05 - INFO - I could use this to generate unique ids
2019-01-02 09:42:05 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:42:05 - INFO - Step 7: richer data for a SKU
2019-01-02 09:42:05 - INFO - Step 8: pull some data from the structure
2019-01-02 09:42:05 - INFO - Type of cover = leather
2019-01-02 09:42:05 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:42:05 - INFO - Uncommenting lines 59 and 60 for Jenny
Redis error: WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by smitco** [comment]
Here is the third output if I change "Jenny" to "Jeny" with no other changes:

(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:43:00 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:43:00 - INFO - Other databases use data embedded in the modules
2019-01-02 09:43:00 - INFO - Step 1: connect to Redis
2019-01-02 09:43:00 - INFO - Here is where we use the connect to redis.
2019-01-02 09:43:00 - INFO - Step 2: cache some data in Redis
2019-01-02 09:43:01 - INFO - Step 2: now I can read it
2019-01-02 09:43:01 - INFO - But I must know the key
2019-01-02 09:43:01 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:43:01 - INFO - Step 3: cache more data in Redis
2019-01-02 09:43:01 - INFO - Step 4: delete from cache
2019-01-02 09:43:01 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:43:01 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:43:02 - INFO - I could use this to generate unique ids
2019-01-02 09:43:02 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:43:02 - INFO - Step 7: richer data for a SKU
2019-01-02 09:43:02 - INFO - Step 8: pull some data from the structure
2019-01-02 09:43:02 - INFO - Type of cover = leather
2019-01-02 09:43:02 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:43:02 - INFO - Changing lines 59 and 60 to Jeny (one n)
2019-01-02 09:43:04 - INFO - Jeny's number: 44307 and zip: 867-5309

**Comment by smitco** [comment]
Last output where I uncommented "Jenny" and her data on the lines lower in the code that I retyped in case there was a whitespace error.

(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:44:43 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:44:43 - INFO - Other databases use data embedded in the modules
2019-01-02 09:44:43 - INFO - Step 1: connect to Redis
2019-01-02 09:44:43 - INFO - Here is where we use the connect to redis.
2019-01-02 09:44:43 - INFO - Step 2: cache some data in Redis
2019-01-02 09:44:43 - INFO - Step 2: now I can read it
2019-01-02 09:44:43 - INFO - But I must know the key
2019-01-02 09:44:43 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:44:43 - INFO - Step 3: cache more data in Redis
2019-01-02 09:44:43 - INFO - Step 4: delete from cache
2019-01-02 09:44:43 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:44:43 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:44:44 - INFO - I could use this to generate unique ids
2019-01-02 09:44:44 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:44:44 - INFO - Step 7: richer data for a SKU
2019-01-02 09:44:44 - INFO - Step 8: pull some data from the structure
2019-01-02 09:44:44 - INFO - Type of cover = leather
2019-01-02 09:44:44 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:44:44 - INFO - Uncommenting lines 87 and 88 for Jenny
Redis error: WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by smitco** [comment]
My brother suggested I see what it does with similar names like Penny and Renny:

Penny seems to shift the indexes by one:
(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:52:26 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:52:26 - INFO - Other databases use data embedded in the modules
2019-01-02 09:52:26 - INFO - Step 1: connect to Redis
2019-01-02 09:52:26 - INFO - Here is where we use the connect to redis.
2019-01-02 09:52:26 - INFO - Step 2: cache some data in Redis
2019-01-02 09:52:26 - INFO - Step 2: now I can read it
2019-01-02 09:52:26 - INFO - But I must know the key
2019-01-02 09:52:26 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:52:26 - INFO - Step 3: cache more data in Redis
2019-01-02 09:52:26 - INFO - Step 4: delete from cache
2019-01-02 09:52:26 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:52:26 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:52:27 - INFO - I could use this to generate unique ids
2019-01-02 09:52:27 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:52:27 - INFO - Step 7: richer data for a SKU
2019-01-02 09:52:27 - INFO - Step 8: pull some data from the structure
2019-01-02 09:52:27 - INFO - Type of cover = leather
2019-01-02 09:52:27 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:52:29 - INFO - Added Penny at phone 9876543 and zip 12345
2019-01-02 09:52:29 - INFO - Added Renny at phone 1478520 and zip 96302
2019-01-02 09:52:29 - INFO - Penny's number: 12345 and zip: None

**Comment by smitco** [comment]
Renny flips the numbers:

(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 09:53:24 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 09:53:24 - INFO - Other databases use data embedded in the modules
2019-01-02 09:53:24 - INFO - Step 1: connect to Redis
2019-01-02 09:53:24 - INFO - Here is where we use the connect to redis.
2019-01-02 09:53:24 - INFO - Step 2: cache some data in Redis
2019-01-02 09:53:25 - INFO - Step 2: now I can read it
2019-01-02 09:53:25 - INFO - But I must know the key
2019-01-02 09:53:25 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 09:53:25 - INFO - Step 3: cache more data in Redis
2019-01-02 09:53:25 - INFO - Step 4: delete from cache
2019-01-02 09:53:25 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 09:53:25 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 09:53:26 - INFO - I could use this to generate unique ids
2019-01-02 09:53:26 - INFO - Redis says 21+1+1-1=22
2019-01-02 09:53:26 - INFO - Step 7: richer data for a SKU
2019-01-02 09:53:26 - INFO - Step 8: pull some data from the structure
2019-01-02 09:53:26 - INFO - Type of cover = leather
2019-01-02 09:53:26 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 09:53:28 - INFO - Added Penny at phone 9876543 and zip 12345
2019-01-02 09:53:28 - INFO - Added Renny at phone 1478520 and zip 96302
2019-01-02 09:53:28 - INFO - Renny's number: 96302 and zip: 1478520

**Comment by smitco** [comment]
Actually now that I look back, all of the phone and zips are flipped.  Whoops. So that still means that Penny's phone didn't get pushed in, I think.

**Comment by ldconejo** [comment]
Hi Courtney,

I think I know what happened: At some point during your development process, you associated the key 'Jenny' with a different type of value, so now it's rejecting you trying to push a string. Add some code to delete the 'Jenny' key and then try pushing the new value again. That should do the trick.

Regards,

Luis

**Comment by smitco** [comment]
I added a flushdb at the end and re-ran the code. Looks like that did the trick. I'll definitely remember that in the future if I get an error, it might stick around in my database until I clear it out.

(pythree) C:\Users\ckastner\UW\Course 2\lesson08\nosql\src>python learnnosql.py
2019-01-02 10:59:58 - INFO - Mongodb example to use data from Furniture module, so get it
2019-01-02 10:59:58 - INFO - Other databases use data embedded in the modules
2019-01-02 10:59:58 - INFO - Step 1: connect to Redis
2019-01-02 10:59:58 - INFO - Here is where we use the connect to redis.
2019-01-02 10:59:58 - INFO - Step 2: cache some data in Redis
2019-01-02 10:59:59 - INFO - Step 2: now I can read it
2019-01-02 10:59:59 - INFO - But I must know the key
2019-01-02 10:59:59 - INFO - The results of r.get: andy@somewhere.com
2019-01-02 10:59:59 - INFO - Step 3: cache more data in Redis
2019-01-02 10:59:59 - INFO - Step 4: delete from cache
2019-01-02 10:59:59 - INFO - r.delete means andy is now: andy@somewhere.com
2019-01-02 10:59:59 - INFO - Step 6: Redis can maintain a unique ID or count very efficiently
2019-01-02 11:00:00 - INFO - I could use this to generate unique ids
2019-01-02 11:00:00 - INFO - Redis says 21+1+1-1=22
2019-01-02 11:00:00 - INFO - Step 7: richer data for a SKU
2019-01-02 11:00:00 - INFO - Step 8: pull some data from the structure
2019-01-02 11:00:00 - INFO - Type of cover = leather
2019-01-02 11:00:00 - INFO - Step 9: add customer data to cache and retrieve
2019-01-02 11:00:02 - INFO - Jenny's number: 867-5309 and zip: 44307
2019-01-02 11:00:02 - INFO - Clear cache with flush
2019-01-02 11:00:02 - INFO - Cache should be clear

**Pull request merged**
