### PR TITLE
 Assignment 8 Redis

### PR DESCRIPTION
**Pull request by Swt16**
Disregard this.

### CODE REVIEW

**Comment by Swt16** [comment]
Assignment 8 Redis Mailroom completed.

**Comment by Swt16** [comment]
Assignment 8 Redis Mailroom completed.

**Comment by ldconejo** [comment]
Hi Shin,

Is this one ready then? I don't see a submission on the course website for the second assignment of lesson 8.

Thanks,

Luis

**Comment by ldconejo** [comment]
Hi Shin,

I will close this pull request for now, we can reopen it once the submission on the course website is ready.

Thanks,

Luis

**Comment by Swt16** [comment]
I have the Mongodb, and Reids ready. I'm currently working on the Neo4j version.

Thanks,
Shin

**Comment by ldconejo** [comment]
Hi Shin,

Great, let me know if you run into any issues with Neo4j.

Regards,

Luis

**Pull request closed without merging**
