### PR TITLE
Lesson07 - mailroom - question for UNION and GROUP BY

### PR DESCRIPTION
**Pull request by wpucilow**
Hi,

I have a question how to perfrom group_by on UNION. In attached code method Main.project.

                query1 =  (Donation
                          .select(Donation.donor.alias('donor'),
                                  fn.SUM((Donation.amount)*factor).alias('total'))
                          .where(
                                    (Donation.amount > min_donation) &
                                    (Donation.amount < max_donation)
                                 )
                          .group_by(Donation.donor)
                         )
                # not concerend by projection & challenge
                query2 =  (Donation
                          .select(Donation.donor.alias('donor'),
                                  (fn.SUM(Donation.amount)).alias('total'))
                          .where(
                                    (Donation.amount <= min_donation) &
                                    (Donation.amount >= max_donation)
                                 )
                          .group_by(Donation.donor)
                         )

                query = ((query1 + query2)
                            .select(
                                SQL('donor'),
                                fn.SUM(SQL('total'))
                            )
                            .group_by(SQL('donor'))
                            .order_by(SQL('donor'))
                    )

then when executing:
                for i in query:
                    pp.pprint("{:30} | {:30}".format(str(i.donor),
                                                     str(i.total)
                                                )
                                    )
  File "run_mailroom_db.py", line 353, in project
    for i in query:
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 1690, in __iter__
    self._ensure_execution()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 1686, in _ensure_execution
    raise ValueError('Query has not been executed.')
ValueError: Query has not been executed.

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Wieslaw,

This in an interesting one as well. If create a compounded query from query1 and query2, for example, if you tried with a factor of 3, you'd get something like this:

```
'============================================================'
'Projected Donors for factor: 3, min: 300.0, max: 3000.0'
'Donor                          | Total                         '
'============================================================'
'Abdul Abdulah                  | 500                           '
'Abdul Abdulah                  | 1500                          '
'Ivan Smirnoff                  | 2000                          '
'Ivan Smirnoff                  | 6000                          '
'Speedy Gonzales                | 1000                          '
'Speedy Gonzales                | 3000                          '
'Toshiro Asai                   | 400                           '
'Toshiro Asai                   | 1200                          '
```

If I understand correctly, what you want to achieve is, for each donor, get the SUM of the original donation PLUS the projected donation (for example, for Abdul Adbulah, it'd be 500 + 1500 = 2000). I honestly don't know if you can do a select on a compounded table. An alternative solution that I can think of is to do it with a single query: 

```
                query1 =  (Donation
                          .select(Donation.donor.alias('donor'),
                                  fn.SUM((Donation.amount)*factor + Donation.amount).alias('total')
                                  )
                          .where(
                                    (Donation.amount > min_donation) &
                                    (Donation.amount < max_donation)
                                 )
                          .group_by(Donation.donor)
                         )
```

For the same example (with a factor of 3) you'd get this:

```
'============================================================'
'Projected Donors for factor: 3, min: 300.0, max: 3000.0'
'Donor                          | Total                         '
'============================================================'
'Abdul Abdulah                  | 2000                          '
'Ivan Smirnoff                  | 8000                          '
'Speedy Gonzales                | 4000                          '
'Toshiro Asai                   | 1600                          '
```

This would achieve the same result as being able to SUM the total column from both table, grouped by donor.

Let me know if this works as a solution.

Thanks,

Luis

**Comment by wpucilow** [comment]
Hi Luis,

Not exactly. I would like to get for each donor the sum of projected donations and the sum of the rest of donations. Please note that projected donations are only those between MIN and MAX, all others will not be multiply by factor.

Example from SQLite:

sqlite> select * from donation;
id|donor_id|amount
1|Speedy Gonzales|10     <---- not concerned by projection because < 30
2|Ivan Smirnoff|20            <---- not concerned by projection because < 30
3|Charles Goldberg|30     <---- not concerned by projection because < 30
4|Toshiro Asai|80
5|Abdul Abdulah|100
6|Speedy Gonzales|200
7|Ivan Smirnoff|400
8|Charles Goldberg|600
9|Toshiro Asai|800
10|Abdul Abdulah|1000
11|Speedy Gonzales|2000
12|Ivan Smirnoff|4000 <---- not concerned by projection because > 3000
SQLite>

and Query I would like to implement in peewee is (factor=2, MIN=30, MAX=3000):

select donor_id, sum(total) from(
select donor_id, sum(amount*2) as total from donation where amount > 30 and amount < 3000 group by donor_id UNION ALL
select donor_id, sum(amount) as total from donation where amount <= 30 or amount >= 3000 group by donor_id ) group by donor_id;

donor_id|sum(total)
Abdul Abdulah|2200
Charles Goldberg|1230
Ivan Smirnoff|4820
Speedy Gonzales|4410
Toshiro Asai|1760

The second query shows total of donation after multiplication factor applied on donations > MIN and < MAX
regards
Wieslaw

**Comment by ldconejo** [comment]
Hi Wieslaw,

I see it now. Let me dig a little deeper and see if there's a way, within Peewee, to do this (the data could be aggregated with a dictionary, but it'd make sense to be able to do the same as with SQL).

Thanks

Luis

**Comment by ldconejo** [comment]
Hi Wieslaw,

Here's the solution, in all its glory. The things that I changed:

- For _query2_, it's one condition OR (not AND) the other, since a donation is either below the minimum limit or over the maximum limit, it can't be both.
- _query_ is being executed (_query.execute(database)_) when you're iterating over the results of the compounded results of _query1_ and _query2_.
- Note that the compounded query results are a dictionary, something you can see when the results are printed(_i['donor']_ and _i['SUM(total)']_).


  ```
      try:
            database.execute_sql('PRAGMA foreign_keys = ON;')
            with database.transaction():
                # part multiplied by factor
                query1 =  (Donation
                          .select(Donation.donor.alias('donor'),
                                  fn.SUM((Donation.amount)*factor).alias('total'))
                          .where(
                                    (Donation.amount > min_donation) &
                                    (Donation.amount < max_donation)
                                 )
                          .group_by(Donation.donor)
                         )
                # not concerend by projection & challenge
                query2 =  (Donation
                          .select(Donation.donor.alias('donor'),
                                  (fn.SUM(Donation.amount)).alias('total'))
                          .where(
                                    (Donation.amount <= min_donation) |
                                    (Donation.amount >= max_donation)
                                 )
                          .group_by(Donation.donor)
                         )

                query = ((query1 + query2)
                            .select(
                                SQL('donor'),
                                fn.SUM(SQL('total'))
                            )
                            .group_by(SQL('donor'))
                            .order_by(SQL('donor'))
                    )

                pp.pprint("="*60)
                pp.pprint("Projected Donors for factor: {}, min: {}, max: {}".format(factor,
                                                                           min_donation,
                                                                           max_donation)
                      )
                pp.pprint('{:30} | {:30}'.format(
                                        'Donor',
                                        'Total'))
                pp.pprint("="*60)
                for i in query.execute(database):
                    pp.pprint("{:30} | {:30}".format(str(i['donor']),
                                                     str(i['SUM(total)'])
                                                )
                                    )


```
Let me know if you have any further questions. Sorry it took so long to figure this one out :-) 

Regards,

Luis

**Comment by wpucilow** [comment]
Wow. Great job indeed. I know I have error message like query not executed but I couldn't find how to execute it. Thank you so much. Good finding. Might be very useful for other compounded queries.

I was about to run through dictionary

                d = {}
                for i in query1+ query2:
                    if i.donor in d.keys():
                        d[i.donor] += i.total
                    else:
                        d[i.donor] = i.total
                
                for k,v in d.items():
                    pp.pprint("{:30} | {:30}".format(str(k),
                                                     str(v)
                                                )
                                    )

but this might be very useful.

Thank you so much. I'm going to upload the assignment. Already started working on Lesson 8.

Wieslaw

**Comment by wpucilow** [comment]
Thank you Luis,
I have send a question to Lesson08 NoSQL example, but it was added to the same pull request # 403
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018/pull/413/
Lesson08 - nosql examples 
wpucilow@plno-pucilowski:/mnt/c/UW_Python_2/Lesson08/nosql/src$ python3.6 learnnosql.py
2018-11-19 20:40:05 - INFO - Configuration file /mnt/c/UW_Python_2/Lesson08/nosql/.config/config.ini
2018-11-19 20:40:05 - INFO - Mongodb example to use data from Furniture module, so get it
2018-11-19 20:40:05 - INFO - Here is where we use the connect to mongodb.
2018-11-19 20:40:05 - INFO - Note use of f string to embed the user & password (from the tuple).
error: 'PosixPath' object is not iterable
Traceback (most recent call last):
  File "learnnosql.py", line 39, in <module>
    showoff_databases()
  File "learnnosql.py", line 25, in showoff_databases
    mongodb_script.run_example(furniture)
  File "/mnt/c/UW_Python_2/Lesson08/nosql/src/mongodb_script.py", line 17, in run_example
    with login_database.login_mongodb_cloud() as client:
  File "/mnt/c/UW_Python_2/Lesson08/nosql/src/login_database.py", line 34, in login_mongodb_cloud
log.info('Login: {} and password: {}'.format(user, pw))
UnboundLocalError: local variable 'user' referenced before assignment


regardsWieslaw

    On ‎Monday‎, ‎November‎ ‎19‎, ‎2018‎ ‎03‎:‎22‎:‎12‎ ‎PM‎ ‎PST, Luis Conejo-Alpizar <notifications@github.com> wrote:  
 
 
Hi Wieslaw,

Here's the solution, in all its glory. The things that I changed:
   
   -    
For query2, it's one condition OR (not AND) the other, since a donation is either below the minimum limit or over the maximum limit, it can't be both.

   -    
query is being executed (query.execute(database)) when you're iterating over the results of the compounded results of query1 and query2.

   -    
Note that the compounded query results are a dictionary, something you can see when the results are printed(i['donor'] and i['SUM(total)']).
       try:
          database.execute_sql('PRAGMA foreign_keys = ON;')
          with database.transaction():
              # part multiplied by factor
              query1 =  (Donation
                        .select(Donation.donor.alias('donor'),
                                fn.SUM((Donation.amount)*factor).alias('total'))
                        .where(
                                  (Donation.amount > min_donation) &
                                  (Donation.amount < max_donation)
                               )
                        .group_by(Donation.donor)
                       )
              # not concerend by projection & challenge
              query2 =  (Donation
                        .select(Donation.donor.alias('donor'),
                                (fn.SUM(Donation.amount)).alias('total'))
                        .where(
                                  (Donation.amount <= min_donation) |
                                  (Donation.amount >= max_donation)
                               )
                        .group_by(Donation.donor)
                       )

              query = ((query1 + query2)
                          .select(
                              SQL('donor'),
                              fn.SUM(SQL('total'))
                          )
                          .group_by(SQL('donor'))
                          .order_by(SQL('donor'))
                  )

              pp.pprint("="*60)
              pp.pprint("Projected Donors for factor: {}, min: {}, max: {}".format(factor,
                                                                         min_donation,
                                                                         max_donation)
                    )
              pp.pprint('{:30} | {:30}'.format(
                                      'Donor',
                                      'Total'))
              pp.pprint("="*60)
              for i in query.execute(database):
                  pp.pprint("{:30} | {:30}".format(str(i['donor']),
                                                   str(i['SUM(total)'])
                                              )
                                  )



Let me know if you have any further questions. Sorry it took so long to figure this one out :-) 

Regards,

Luis

**Comment by wpucilow** [comment]
Hi Luis,

Additionally to the assignement I wonder if there is a way to implement DB export to JSON. Is there a way to export Database from peewee/SQLite to JSON. We did by wrapping classes, then running export from object.
 
rgds
Wieslaw

**Pull request closed without merging**
