### PR TITLE
Question to Lesson07 peewee join tables

### PR DESCRIPTION
**Pull request by wpucilow**
Hi,

I'm trying to run join between tables in peewee, but having some problem.

Join in SQLite works fine:

$ sqlite3 personjob.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.

sqlite> SELECT person.person_name, job.job_name, department.department_name, job.salary, job.duration, department.department_manager
   ...> FROM person
   ...> INNER JOIN job on person.person_name = job.person_employed_id
   ...> LEFT OUTER JOIN department on job.job_department_id = department.department_number;

Andrew|Analyst|Analyst|65500|495|Ryan Duck
Andrew|Senior analyst|Analyst|70000|1359|Ryan Duck
Andrew|Senior business analyst|Business|80000|3715|Monica Lows
Peter|Admin supervisor|Administration|45900|770|Pamela Alcaline
Peter|Admin manager|Administration|45900|1148|Pamela Alcaline
sqlite>

but having problems how to implement below sql in peewee:

SELECT person.person_name, job.job_name, department.department_name, job.salary, job.duration, department.department_manager
FROM person 
INNER JOIN job on person.person_name = job.person_employed_id
LEFT OUTER JOIN department on job.job_department_id = department.department_number;

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Wieslaw,

Your code was pretty close, here's what it should look like for your first join:

`    try:
        database.connect()
        database.execute_sql('PRAGMA foreign_keys = ON;')
        query = (Person
                .select(Person.person_name,
                        Job.job_name,
                        Department.department_name.alias('department_name'),
                        Job.salary,
                        Job.duration,
                        Department.department_manager)
                .join(Job,
                      JOIN.INNER,
                      on=(Person.person_name == Job.person_employed_id)) # joins person -> job
                .join(Department, 
                      JOIN.LEFT_OUTER,
                      on=(Job.job_department_id == Department.department_number)) # joins job -> department
                .objects()
        )
    
        pp('{:15} - {:15} - {:15} - {:10} - {:10} - {:10}'.format(
                                    'Person',
                                    'Job',
                                    'Department',
                                    'Salary',
                                    'Duration',
                                    'Manager')
                                )
        for job in query:
                pp('{:15} - {:15} - {:15} - {:10} - {:10} - {:10}'.format(
                                            job.person_name,
                                            job.job_name,
                                            job.department_name,
                                            job.salary,
                                            job.duration,
                                            job.department_manager
                                        )
                   )
    except Exception as e:
        logger.info(e)
    finally:
        database.close()`

The changes that were made are the following:

- Format of the _on=_ statement: Not in quotes, the comparison operator should be _==_.
- Added _objects()_ at the end of the query. You will find this referred to as _naive()_ in previous versions of Peewee. I'm not an expert in Peewee, in general, you need _objects()_ to be able to access attributes from the tables that are joined.
- When printing the query results, all attributes belong to _job_ (_for job in query_).

Let me know if this helps. Thank you for submitting this code, it was very interesting to debug it!

Regards,

Luis

**Comment by wpucilow** [comment]
Thank you Idconejo for the answer. I'm confused about below statement: 

"When printing the query results, all attributes belong to job (for job in query)."

Why all the attributes belong to job? In query we do select from Person, Job and Department. What makes all columns belong to single column job and why to job and not any other?

.select(Person.person_name,
                        Job.job_name,
                        Department.department_name.alias('department_name'),
                        Job.salary,
                        Job.duration,
                        Department.department_manager)

regards
Wieslaw

**Comment by wpucilow** [comment]
Thank you. My missed.  Just one more question. When peewee runs the sql query? So far I can see the following sequence of actions:

database.connect()

database.execute_sql('PRAGMA foreign_keys = ON;')

query = (<building query here>)

for result in query:
       print(result.colum)

There is no explicit run(query) statement. How database.execute_sql() knows what is the SQL statement to run?

**Comment by ldconejo** [comment]
Another good question! It runs as part of assigning a value to the variable _query_. I'm not familiar with the inner workings of it, but I assume it goes like this:

- Parsing of your select statement and other elements you're assigning to the variable _query_.
- Execution the query.
- Object with the results (not the query itself) is assigned to the variable _query_.

Note that _query_ could also have a different, more explicit name, such as _query_results_.

Regards,

Luis

**Comment by wpucilow** [comment]
Thanks Luis,

I can imaging that 

database.execute_sql('PRAGMA foreign_keys = ON;')

acts on the sql in query variable defined below. However I'm confused because there is no any indent for query= statement, which would define the scope of database.execute_sql, assign sql statement for execution. Anyway I'm taking it for granted, commands order here plays the role.

regards
Wieslaw

**Comment by wpucilow** [comment]
In order to avoid another topics in Discussion forum I'm sending this repo for a new question directly
report() - type object 'Donation' has no attribute 'select' by wpucilow · Pull Request #399 · UWPCE-PythonCert-ClassRepos/SP_Online_Course2_2018

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
report() - type object 'Donation' has no attribute 'select' by wpucilow ...


 |

 |

 |





regardsWieslaw


    On ‎Tuesday‎, ‎November‎ ‎13‎, ‎2018‎ ‎11‎:‎30‎:‎37‎ ‎AM‎ ‎PST, Luis Conejo-Alpizar <notifications@github.com> wrote:  
 
 
Another good question! It runs as part of assigning a value to the variable query. I'm not familiar with the inner workings of it, but I assume it goes like this:
   
   - Parsing of your select statement and other elements you're assigning to the variable query.
   - Execution the query.
   - Object with the results (not the query itself) is assigned to the variable query.

Note that query could also have a different, more explicit name, such as query_results.

Regards,

Luis

**Comment by wpucilow** [comment]
Hi Luis,
I have uploaded "mailroom" which is almost done. However I have a question for peewee UNION and exactly Group by on the UNION. More details in the new repo. 
On the other hand I would like to ask how to perform sqlite3 DB backup to JSON from peewee. What is the best approach.

regardsWieslaw

**Pull request closed without merging**
