### PR TITLE
lesson07, part2: add to update and delete

### PR DESCRIPTION
**Pull request by mayc4t**
Note, please ignore the lesson08 part, I'm still working on that.

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Lily,

Could you add a submission for the first assignment of lesson 7? It seems you only submitted for the second assignment. I need you to submit on both to be able to grade it. Other than that, great work and nice touch to implement it as a test.

Thanks,

Luis

**Comment by mayc4t** [comment]
FYI, I did add the submission for the first part of lesson 07 some time
last week.
Thanks,
Lily

**Comment by ldconejo** [comment]
Hi Lily,

Thanks for letting me know. I have now graded the assignment.

Regards,

Luis

**Comment by mayc4t** [comment]
Hi Luis,

I've just checked the course progress and for lesson07 I've only received
8/16 points. I thought I had completed all of lesson07.

Thanks,
Lily

**Pull request merged**
